onlyBuiltDependencies:
  - /
  - '@'
  - '@parcel/watcher'
  - '@swc/core'
  - a
  - c
  - e
  - esbuild
  - h
  - l
  - p
  - r
  - sharp
  - t
  - unrs-resolver
  - w

overrides:
  '@babel/core@<=7.29.0': '>=7.29.6'
  '@humanfs/node@<0.16.8': '>=0.16.8'
  '@vitest/mocker@>=2.1.0 <4.1.11': '>=4.1.11'
  baseline-browser-mapping@>=2.0.0 <2.11.0: '>=2.11.0'
  brace-expansion@<1.1.16: '>=1.1.16'
  brace-expansion@<1.1.17: '>=1.1.17'
  brace-expansion@<1.1.18: '>=1.1.18'
  brace-expansion@>=3.0.0 <5.0.7: '>=5.0.7'
  brace-expansion@>=4.0.0 <5.0.8: '>=5.0.8'
  brace-expansion@>=4.0.0 <5.0.9: '>=5.0.9'
  brace-expansion@>=5.0.0 <5.0.6: '>=5.0.6'
  browserslist@<=4.28.6: '>=4.28.7'
  esbuild@>=0.27.3 <0.28.1: '>=0.28.1'
  fflate@>=0.7.0 <0.7.5: '>=0.7.5'
  icu-minify@<=4.9.1: '>=4.9.2'
  js-yaml@>=4.0.0 <4.3.0: '>=4.3.0'
  js-yaml@>=4.0.0 <4.3.1: '>=4.3.1'
  js-yaml@>=4.0.0 <4.3.2: '>=4.3.2'
  js-yaml@>=4.0.0 <=4.1.1: '>=4.2.0'
  nanoid@<3.3.12: '>=3.3.12'
  nanoid@<3.3.16: '>=3.3.16'
  nanoid@<3.3.18: '>=3.3.18'
  next-intl@<4.9.1: '>=4.9.1'
  next-intl@<=4.9.1: '>=4.9.2'
  next@>=16.0.0 <16.2.11: '>=16.2.11'
  next@>=16.0.0 <16.2.5: '>=16.2.5'
  next@>=16.0.0 <16.2.6: '>=16.2.6'
  next@>=16.0.0 <16.3.3: '>=16.3.3'
  next@>=16.0.0-beta.0 <16.1.7: '>=16.1.7'
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  next@>=16.0.1 <16.1.7: '>=16.1.7'
  postcss@<8.5.10: '>=8.5.10'
  postcss@<=8.5.11: '>=8.5.12'
  postcss@<=8.5.17: '>=8.5.18'
  postcss@<=8.5.22: '>=8.5.23'
  sharp@<0.35.0: '>=0.35.0'
  sharp@<0.35.4: '>=0.35.4'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=7.0.0 <=7.3.4: '>=7.3.5'
  vite@>=7.1.0 <=7.3.1: '>=7.3.2'
  vitest@>=2.1.0 <4.1.11: '>=4.1.11'
  vitest@>=4.0.0 <4.1.0: '>=4.1.0'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'
  ws@>=8.0.0 <8.21.0: '>=8.21.0'
